live_config_reload = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x303030"
index = 18

[[colors.indexed_colors]]
color = "0x353535"
index = 19

[[colors.indexed_colors]]
color = "0xb2ccd6"
index = 20

[[colors.indexed_colors]]
color = "0xeeffff"
index = 21

[colors.bright]
black = "#101010"
blue = "#9db3c9"
cyan = "#abc6d1"
green = "#a5c99d"
magenta = "#c79dbf"
red = "#c99f9d"
white = "0xeeffff"
yellow = "#c9c19d"

[colors.cursor]
cursor = "#737373"
text = "#e0e0e0"

[colors.normal]
black = "#101010"
blue = "#9db3c9"
cyan = "#abc6d1"
green = "#a5c99d"
magenta = "#c79dbf"
red = "#c99f9d"
white = "0xeeffff"
yellow = "#c9c19d"

[colors.primary]
background = "#101010"
foreground = "#c9c5c1"

# [cursor.style]
# nano_mode_style = "Beam"
# shape = "Beam"

[env]
TERM = "alacritty"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 1.0

[window.padding]
# decoration = "none"
# dynamic_padding = true
x = 25
y = 25
